version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: wurstmeister/kafka:2.13-2.8.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: "yes"
    depends_on:
      - zookeeper

  akhq:
    image: tchiotludo/akhq:0.26.0
    ports:
      - "8082:8080"
    # environment:
    #   - "AKHQ_CONNECTIONS_KAFKA-cluster_BOOTSTRAPSERVERS=kafka:9092"
    #   - "AKHQ_CONNECTIONS_KAFKA-cluster_NAME=kafka-cluster"
    #   - "AKHQ_SECURITY_DEFAULTGROUPS=admin"
    volumes:
      - ./akhq-config.yaml:/app/application.yml
    depends_on:
      - kafka

  jobmanager:
    build: ./flink
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    ports:
      - "8081:8081"
    volumes:
      - ./flink-jobs:/opt/flink/jobs

  taskmanager:
    build: ./flink
    command: taskmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
      - TASK_MANAGER_NUMBER_OF_TASK_SLOTS=4
    depends_on:
      - jobmanager

  rabbitmqproducer:
    build: ./rabbitmq-producer
    depends_on:
      - rabbitmq

  kafkaproducer:
    build: ./kafka-producer
    depends_on:
      - kafka


